workflow:
  continue_runs: false
  create_database: true
  import_raw_data: true
  find_features: true
  search_data: true
  recalibrate_data: false
  align: false
  match: false
  lfq_quantification: false
general:
  n_processes: 2
  modfile_hash: ada3155a45419abed7c74afd393d1842
experiment:
  results_path: null
  shortnames:
  - filename_prefix_01
  - filename_prefix_02
  - filename_prefix_03
  - filename_prefix_04
  - filename_prefix_05
  - filename_prefix_06
  - filename_prefix_07
  - filename_prefix_08
  - filename_prefix_09
  - filename_prefix_10
  - filename_prefix_11
  file_paths:
  - work_Dir/filename_prefix_01.raw
  - work_Dir/filename_prefix_02.raw
  - work_Dir/filename_prefix_03.raw
  - work_Dir/filename_prefix_04.raw
  - work_Dir/filename_prefix_05.raw
  - work_Dir/filename_prefix_06.raw
  - work_Dir/filename_prefix_07.raw
  - work_Dir/filename_prefix_08.raw
  - work_Dir/filename_prefix_09.raw
  - work_Dir/filename_prefix_10.raw
  - work_Dir/filename_prefix_11.raw
  sample_group:
  - filename_prefix_01
  - filename_prefix_02
  - filename_prefix_03
  - filename_prefix_04
  - filename_prefix_05
  - filename_prefix_06
  - filename_prefix_07
  - filename_prefix_08
  - filename_prefix_09
  - filename_prefix_10
  - filename_prefix_11
  matching_group:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  fraction:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  database_path: work_Dir/output.hdf
  fasta_paths:
  - /path/to/protein.fasta
raw:
  n_most_abundant: 400
  use_profile_ms1: false
fasta:
  mods_fixed:
  - cC
  mods_fixed_terminal: []
  mods_variable:
  - oxM
  mods_variable_terminal: []
  mods_fixed_terminal_prot: []
  mods_variable_terminal_prot:
  - a<^
  n_missed_cleavages: 3
  pep_length_min: 7
  pep_length_max: 60
  isoforms_max: 1024
  n_modifications_max: 1
  pseudo_reverse: false
  AL_swap: false
  KR_swap: false
  protease: trypsin/p
  spectra_block: 100000
  fasta_block: 1000
  save_db: true
  fasta_size_max: 102
features:
  max_gap: 2
  centroid_tol: 8
  hill_length_min: 3
  hill_split_level: 1.3
  iso_split_level: 1.3
  hill_smoothing: 1
  hill_check_large: 40
  iso_charge_min: 1
  iso_charge_max: 6
  iso_n_seeds: 100
  hill_nboot_max: 300
  hill_nboot: 150
  iso_mass_range: 5
  iso_corr_min: 0.6
  map_mz_range: 1.5
  map_rt_range: 0.5
  map_mob_range: 0.3
  map_n_neighbors: 5
  search_unidentified: false
search:
  prec_tol: 20
  frag_tol: 15
  top_n: 5
  min_frag_hits: 7
  ppm: True
  calibrate: false
  calibration_std_prec: 5
  calibration_std_frag: 5
  parallel: true
  peptide_fdr: 0.01
  protein_fdr: 0.01
  recalibration_min: 100
score:
  method: random_forest
  ml_ini_score: generic_score
calibration:
  outlier_std: 3
  calib_n_neighbors: 100
  calib_mz_range: 2000
  calib_rt_range: 0.5
  calib_mob_range: 0.3
matching:
  match_p_min: 0.05
  match_d_min: 3
  match_group_tol: 0
quantification:
  max_lfq: true
  lfq_ratio_min: 1
  mode: ms1_int_sum_apex
